import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './overrides.css';

const initialResume = {
  personal_info: { name: 'Siddhanta Mallick', phone: '+91 9359151422', email: { url: 'x@x.com', display: 'sid.mallick1947@gmail.com' }, linkedin: { url: 'https://linkedin.com/in/...', display: 'linkedin.com/siddhanta-mallick' }, github: { url: 'https://github.com/...', display: 'github.com/siddhanta-mallick' } },
  objective: 'Aspiring Software Engineer with strong skills in full-stack development and machine learning. Committed to writing clean, efficient, and maintainable code to create practical solutions that make a difference.',
  education: [{ institution: 'Manipal Institute of Technology', location: 'Bengaluru, India', degree: 'Bachelor of Technology in Computer Science, CGPA: 8.87', duration: 'Aug. 2023 -- May 2027' }],
  skills: [{ title: 'Languages', items: ['C', 'C++', 'Rust', 'Java', 'Python', 'JavaScript', 'SQL', 'HTML', 'CSS'] }, { title: 'Web Development', items: ['Node.js', 'Express.js', 'Flask', 'Django', 'PostgreSQL', 'MongoDB', 'React.js', 'RESTful APIs'] }, { title: 'Machine Learning', items: ['Scikit-learn', 'TensorFlow', 'Keras', 'NumPy', 'Pandas', 'Deep Learning'] }, { title: 'Cloud Computing', items: ['AWS', 'Docker', 'Serverless Architecture'] }, { title: 'Developer Tools', items: ['Linux (Bash)', 'Git', 'CMake', 'LLDB', 'GDB', 'Postman'] }],
  projects: [{ title: 'C++ NeuroEvolution (NEAT) Reinforcement Learning Framework', tech_stack: 'C++, CMake, CatchV2', duration: '', points: ['Built a modular, from-scratch C++ implementation of the NEAT evolutionary algorithm.', 'Developed a custom translation engine to turn genetic structures into working neural networks.', 'Designed cache-efficient graph structures to optimize feedforward evaluation.'] }, { title: 'Pendulum-on-Cart Control Simulation', tech_stack: 'C++, CUDA, SFML, CMake', duration: '', points: ['Engineered a high-performance 2D physics engine for inverted pendulum dynamics.', 'Accelerated agent training with custom CUDA kernels for 1,000 parallel simulations.'] }, { title: 'OpenRecall', tech_stack: 'Python, Django, React, AWS S3, Docker', duration: '', points: ['Automated resume and cover letter creation by analyzing job posts with LLMs.', 'Reduced manual editing time by 70% through keyword matching.'] }, { title: 'Tailor Docs', tech_stack: 'Python, Flask, React, PostgreSQL, Docker', duration: 'June 2020 -- Present', points: ['Built an ATS-friendly resume and cover letter generator.', 'Extracted job keywords through web scraping and LLMs.'] }, { title: 'Delta LB - Lightweight Application Load Balancer', tech_stack: 'Rust, Docker, EC2', duration: '', points: ['Developed a full-stack application with Flask and React.', 'Implemented GitHub OAuth and repository collaboration visualizations.'] }],
};

const initialDescription = 'Figma is looking for a product designer to make creative work more collaborative. You will partner with researchers, engineers, and product leads to set product direction, turn complex workflows into clear interactions, and raise the quality bar for millions of people making things together.';
function LeafMark() { return <span className="leaf-mark" aria-hidden="true"><i /><i /><i /></span>; }
function setAt(items, index, key, value) { return items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item); }

function ResumePaper({ resume }) {
  const { personal_info: info, education, skills, projects } = resume;
  return <article className="resume-paper">
    <header className="paper-head">
      <h2>{info.name}</h2>
      <p className="paper-contact">
        <span>{info.phone}</span><span className="contact-separator" aria-hidden="true">|</span>
        <a href={`mailto:${info.email.url}`}>{info.email.display}</a><span className="contact-separator" aria-hidden="true">|</span>
        <a href={info.linkedin.url}>{info.linkedin.display}</a><span className="contact-separator" aria-hidden="true">|</span>
        <a href={info.github.url}>{info.github.display}</a>
      </p>
    </header>
    <section><h3>Objective</h3><p className="paper-objective">{resume.objective}</p></section>
    <section><h3>Education</h3>{education.map((entry, index) => (entry.institution || entry.location || entry.degree || entry.duration) && <div className="paper-entry" key={index}>
      <div className="paper-entry-line"><strong>{entry.institution}</strong><span>{entry.location}</span></div>
      <div className="paper-entry-line paper-entry-detail"><i>{entry.degree}</i><i>{entry.duration}</i></div>
    </div>)}</section>
    <section><h3>Skills</h3>{skills.map((skill, index) => (skill.title || skill.items.some(Boolean)) && <p className="skill-line" key={index}><b>{skill.title}:</b> {skill.items.filter(Boolean).join(', ')}</p>)}</section>
    <section><h3>Projects</h3>{projects.map((project, index) => (project.title || project.tech_stack || project.duration || project.points.some(Boolean)) && <div className="paper-project" key={index}>
      <div className="paper-project-heading"><p><strong>{project.title}</strong> <span aria-hidden="true">|</span> <i>{project.tech_stack}</i></p><span>{project.duration}</span></div>
      <ul>{project.points.map((point, pointIndex) => point && <li key={pointIndex}>{point}</li>)}</ul>
    </div>)}</section>
  </article>;
}

function JobDescription({ description, setDescription }) {
  return <div className="panel"><div className="panel-intro"><h2>Bring the role into focus.</h2><p>Paste the final job description you want this resume to answer. This layout intentionally does not scrape job URLs.</p></div><label className="field-label">Job description<textarea className="job-description" value={description} onChange={event => setDescription(event.target.value)} /></label><div className="verification"><span>✓</span><p><b>Ready to tailor</b><br />Use this final text when you generate or refine the resume.</p></div></div>;
}

function EditDetails({ resume, setResume }) {
  const updateInfo = (key, value) => setResume({ ...resume, personal_info: { ...resume.personal_info, [key]: value } });
  const addEducation = () => setResume({ ...resume, education: [...resume.education, { institution: 'New institution', location: '', degree: '', duration: '' }] });
  const addSkill = () => setResume({ ...resume, skills: [...resume.skills, { title: 'New skill group', items: [] }] });
  const addProject = () => setResume({ ...resume, projects: [...resume.projects, { title: 'New project', tech_stack: '', duration: '', points: [''] }] });
  const addProjectPoint = index => setResume({ ...resume, projects: setAt(resume.projects, index, 'points', [...resume.projects[index].points, 'New bullet point']) });
  const removeEducation = index => setResume({ ...resume, education: resume.education.map((entry, entryIndex) => entryIndex === index ? { institution: '', location: '', degree: '', duration: '' } : entry) });
  const removeSkill = index => setResume({ ...resume, skills: resume.skills.map((skill, skillIndex) => skillIndex === index ? { title: '', items: [] } : skill) });
  const removeProject = index => setResume({ ...resume, projects: resume.projects.map((project, projectIndex) => projectIndex === index ? { title: '', tech_stack: '', duration: '', points: [''] } : project) });
  const updateProjectPoint = (projectIndex, pointIndex, value) => setResume({ ...resume, projects: setAt(resume.projects, projectIndex, 'points', resume.projects[projectIndex].points.map((point, index) => index === pointIndex ? value : point)) });
  return <div className="panel edit-panel"><div className="panel-intro"><h2>Edit the generated details.</h2><p>Changes appear in the preview immediately. Add any entry that belongs in this version.</p></div>
    <fieldset><legend>Personal information</legend><div className="two-fields"><label>Name<input value={resume.personal_info.name} onChange={event => updateInfo('name', event.target.value)} /></label><label>Phone<input value={resume.personal_info.phone} onChange={event => updateInfo('phone', event.target.value)} /></label><label>Email shown<input value={resume.personal_info.email.display} onChange={event => updateInfo('email', { ...resume.personal_info.email, display: event.target.value })} /></label><label>Email URL<input value={resume.personal_info.email.url} onChange={event => updateInfo('email', { ...resume.personal_info.email, url: event.target.value })} /></label><label>LinkedIn shown<input value={resume.personal_info.linkedin.display} onChange={event => updateInfo('linkedin', { ...resume.personal_info.linkedin, display: event.target.value })} /></label><label>LinkedIn URL<input value={resume.personal_info.linkedin.url} onChange={event => updateInfo('linkedin', { ...resume.personal_info.linkedin, url: event.target.value })} /></label><label>GitHub shown<input value={resume.personal_info.github.display} onChange={event => updateInfo('github', { ...resume.personal_info.github, display: event.target.value })} /></label><label>GitHub URL<input value={resume.personal_info.github.url} onChange={event => updateInfo('github', { ...resume.personal_info.github, url: event.target.value })} /></label></div></fieldset>
    <fieldset><legend>Objective</legend><textarea value={resume.objective} onChange={event => setResume({ ...resume, objective: event.target.value })} /></fieldset>
    <EditorGroup title="Education" onAdd={addEducation}>{resume.education.map((entry, index) => (entry.institution || entry.location || entry.degree || entry.duration) && <div className="entry-grid" key={index}><label>Institution<input value={entry.institution} onChange={event => setResume({ ...resume, education: setAt(resume.education, index, 'institution', event.target.value) })} /></label><label>Location<input value={entry.location} onChange={event => setResume({ ...resume, education: setAt(resume.education, index, 'location', event.target.value) })} /></label><label>Degree<input value={entry.degree} onChange={event => setResume({ ...resume, education: setAt(resume.education, index, 'degree', event.target.value) })} /></label><label>Duration<input value={entry.duration} onChange={event => setResume({ ...resume, education: setAt(resume.education, index, 'duration', event.target.value) })} /></label><div className="entry-actions"><button type="button" className="remove-entry" onClick={() => removeEducation(index)}>Remove education</button></div></div>)}</EditorGroup>
    <EditorGroup title="Skills" onAdd={addSkill}>{resume.skills.map((skill, index) => (skill.title || skill.items.some(Boolean)) && <div className="entry-grid skills-entry" key={index}><label>Group title<input value={skill.title} onChange={event => setResume({ ...resume, skills: setAt(resume.skills, index, 'title', event.target.value) })} /></label><label>Items, separated by commas<textarea value={skill.items.join(', ')} onChange={event => setResume({ ...resume, skills: setAt(resume.skills, index, 'items', event.target.value.split(',').map(item => item.trim())) })} /></label><div className="entry-actions"><button type="button" className="remove-entry" onClick={() => removeSkill(index)}>Remove skill group</button></div></div>)}</EditorGroup>
    <EditorGroup title="Projects" onAdd={addProject}>{resume.projects.map((project, index) => (project.title || project.tech_stack || project.duration || project.points.some(Boolean)) && <div className="project-entry" key={index}><div className="two-fields"><label>Project title<input value={project.title} onChange={event => setResume({ ...resume, projects: setAt(resume.projects, index, 'title', event.target.value) })} /></label><label>Tech stack<input value={project.tech_stack} onChange={event => setResume({ ...resume, projects: setAt(resume.projects, index, 'tech_stack', event.target.value) })} /></label><label>Duration<input value={project.duration} onChange={event => setResume({ ...resume, projects: setAt(resume.projects, index, 'duration', event.target.value) })} /></label></div><div className="project-bullets"><p>Bullet points</p>{project.points.map((point, pointIndex) => point && <div className="bullet-field" key={pointIndex}><textarea value={point} onChange={event => updateProjectPoint(index, pointIndex, event.target.value)} /><button type="button" className="remove-entry" onClick={() => updateProjectPoint(index, pointIndex, '')}>Remove bullet</button></div>)}</div><div className="entry-actions"><button type="button" className="add-entry" onClick={() => addProjectPoint(index)}>Add bullet point</button><button type="button" className="remove-entry" onClick={() => removeProject(index)}>Remove project</button></div></div>)}</EditorGroup>
  </div>;
}

function EditorGroup({ title, onAdd, children }) { return <fieldset className="repeat-group"><legend>{title}</legend>{children}<button type="button" className="add-entry" onClick={onAdd}>Add {title.slice(0, -1).toLowerCase()}</button></fieldset>; }
function CustomPrompt({ prompt, setPrompt }) { return <div className="panel"><div className="panel-intro"><h2>Give the model a direction.</h2><p>Add a specific request for the next refinement, such as a STAR rewrite, a more formal tone, or a fact that should appear in a project.</p></div><label className="field-label">Custom request<textarea className="prompt-box" value={prompt} onChange={event => setPrompt(event.target.value)} placeholder="For the Tailor Docs project, make the strongest bullet follow the STAR method and include the 70% reduction in editing time." /></label><p className="privacy-note">This instruction helps generate the next version. It is not saved in tailoring history.</p><button className="primary">Refine resume</button></div>; }

function App() {
  const [tab, setTab] = useState('Job description');
  const [resume, setResume] = useState(initialResume);
  const [description, setDescription] = useState(initialDescription);
  const [prompt, setPrompt] = useState('');
  return <main className="workspace"><header className="topbar"><div className="brand"><LeafMark /> Tailorwood</div><div className="workspace-status"><b>Figma</b><span>Product designer</span><em>93 fit</em></div><div><button className="quiet">Save draft</button><button className="primary">Save to history</button></div></header><div className="workspace-body"><section className="editor"><div className="editor-tabs" role="tablist">{['Job description', 'Edit details', 'Custom prompt'].map(item => <button key={item} className={tab === item ? 'active' : ''} role="tab" aria-selected={tab === item} onClick={() => setTab(item)}>{item}</button>)}</div>{tab === 'Job description' && <JobDescription description={description} setDescription={setDescription} />}{tab === 'Edit details' && <EditDetails resume={resume} setResume={setResume} />}{tab === 'Custom prompt' && <CustomPrompt prompt={prompt} setPrompt={setPrompt} />}</section><section className="preview-stage"><div className="preview-toolbar"><p>Live preview <span>Unsaved changes</span></p><button>Download PDF</button></div><ResumePaper resume={resume} /><p className="preview-caption">The final PDF is generated from this edited resume.</p></section></div></main>;
}
createRoot(document.getElementById('root')).render(<App />);
